"""add owner id to applications

Revision ID: 134d00cb854b
Revises: 5d9e4b8bc432
Create Date: 2026-09-01 14:38:29.992442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134d00cb854b'
down_revision: Union[str, Sequence[str], None] = '5d9e4b8bc432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications") as batch_op:
        batch_op.add_column(
            sa.Column("owner_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_applications_owner_id_users",
            "Users",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('issued_by', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'owner_id')
    # ### end Alembic commands ###
