"""add users deleted_at

Revision ID: 5cb7c8080a8a
Revises: c550ada7f30e
Create Date: 2026-09-03 19:51:54.274196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb7c8080a8a'
down_revision: Union[str, Sequence[str], None] = 'c550ada7f30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'deleted_at')
    # ### end Alembic commands ###
