"""adding issuer to the Application Model

Revision ID: a389d5b65e94
Revises: 5d26d7291c4e
Create Date: 2026-08-23 14:50:03.093711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a389d5b65e94'
down_revision: Union[str, Sequence[str], None] = '5d26d7291c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'applications', 
        sa.Column('issued_by', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'issued_by')
    # ### end Alembic commands ###
