"""remove issued_by

Revision ID: c550ada7f30e
Revises: 134d00cb854b
Create Date: 2026-09-03 19:23:22.323827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c550ada7f30e'
down_revision: Union[str, Sequence[str], None] = '134d00cb854b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'issued_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('issued_by', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
